var { createClient } = require('@supabase/supabase-js');

module.exports = async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', 'https://inveritaslaw.com');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
  if (req.method === 'OPTIONS') return res.status(200).end();

  var SUPABASE_URL = process.env.SUPABASE_URL;
  var SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!SUPABASE_URL || !SUPABASE_KEY) {
    return res.status(500).json({ error: 'Server not configured' });
  }

  // Auth check
  var authHeader = req.headers.authorization || '';
  var token = authHeader.replace('Bearer ', '');
  if (!token) return res.status(401).json({ error: 'Not authenticated' });

  var sb = createClient(SUPABASE_URL, SUPABASE_KEY);
  var authResult = await sb.auth.getUser(token);
  if (authResult.error || !authResult.data.user) {
    return res.status(401).json({ error: 'Invalid session' });
  }
  var userId = authResult.data.user.id;

  try {
    // GET /api/cases?profile=true — return user profile (tier check)
    if (req.method === 'GET' && req.query.profile === 'true') {
      var profileResult = await sb.from('user_profiles')
        .select('subscription_tier, analyses_this_month, stripe_customer_id')
        .eq('user_id', userId).single();
      return res.status(200).json({ profile: profileResult.data || { subscription_tier: 'none', analyses_this_month: 0 } });
    }

    // GET /api/cases — list all cases for user
    if (req.method === 'GET' && !req.query.id) {
      var status = req.query.status || null;
      var q = sb.from('cases')
        .select('*, case_analyses(id, version, created_at, trigger_reason), evidence(id)')
        .eq('user_id', userId)
        .order('updated_at', { ascending: false });
      if (status) q = q.eq('status', status);

      var { data, error } = await q;
      if (error) throw error;

      // Transform: add counts
      var cases = (data || []).map(function(c) {
        return Object.assign({}, c, {
          analysis_count: c.case_analyses ? c.case_analyses.length : 0,
          evidence_count: c.evidence ? c.evidence.length : 0,
          latest_analysis_date: c.case_analyses && c.case_analyses.length > 0
            ? c.case_analyses.sort(function(a, b) { return b.version - a.version; })[0].created_at
            : null,
          case_analyses: undefined,
          evidence: undefined
        });
      });

      return res.status(200).json({ cases: cases });
    }

    // GET /api/cases?id=xxx — get single case with full data
    if (req.method === 'GET' && req.query.id) {
      var caseId = req.query.id;

      // Validate UUID format
      if (!caseId || caseId === 'null' || caseId === 'undefined' || !/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(caseId)) {
        return res.status(400).json({ error: 'Invalid case ID' });
      }

      var { data: caseData, error: caseErr } = await sb.from('cases')
        .select('*')
        .eq('id', caseId)
        .eq('user_id', userId)
        .single();
      if (caseErr) throw caseErr;
      if (!caseData) return res.status(404).json({ error: 'Case not found' });

      var { data: analyses } = await sb.from('case_analyses')
        .select('*')
        .eq('case_id', caseId)
        .eq('user_id', userId)
        .order('version', { ascending: false });

      var { data: evidenceList } = await sb.from('evidence')
        .select('*')
        .eq('case_id', caseId)
        .eq('user_id', userId)
        .order('created_at', { ascending: false });

      return res.status(200).json({
        case: caseData,
        analyses: analyses || [],
        evidence: evidenceList || []
      });
    }

    // POST /api/cases — create new case
    if (req.method === 'POST') {
      var body = req.body || {};
      var title = String(body.title || '').slice(0, 200);
      if (!title) return res.status(400).json({ error: 'Title is required' });

      var newCase = {
        user_id: userId,
        case_number: '', // auto-generated by trigger
        title: title,
        case_type: String(body.case_type || 'criminal').slice(0, 50),
        status: 'active',
        state: body.state ? String(body.state).slice(0, 100) : null,
        county: body.county ? String(body.county).slice(0, 200) : null,
        charge: body.charge ? String(body.charge).slice(0, 300) : null,
        jurisdiction: body.jurisdiction ? String(body.jurisdiction).slice(0, 200) : null,
        court: body.court ? String(body.court).slice(0, 200) : null,
        filing_date: body.filing_date || null,
        next_hearing: body.next_hearing || null,
        description: body.description ? String(body.description).slice(0, 5000) : null,
        tags: Array.isArray(body.tags) ? body.tags.slice(0, 10).map(function(t) { return String(t).slice(0, 50); }) : []
      };

      var { data, error } = await sb.from('cases').insert(newCase).select().single();
      if (error) throw error;

      await logAdminAudit(sb, userId, 'case_created', 'case', data.id, { title: title });

      return res.status(201).json({ case: data });
    }

    // PUT /api/cases — update case
    if (req.method === 'PUT') {
      var body = req.body || {};
      var caseId = body.id || req.query.id;
      if (!caseId) return res.status(400).json({ error: 'Case ID required' });

      // Verify ownership
      var { data: existing } = await sb.from('cases')
        .select('id')
        .eq('id', caseId)
        .eq('user_id', userId)
        .single();
      if (!existing) return res.status(404).json({ error: 'Case not found' });

      var updates = {};
      if (body.title) updates.title = String(body.title).slice(0, 200);
      if (body.status) updates.status = String(body.status).slice(0, 20);
      if (body.state) updates.state = String(body.state).slice(0, 100);
      if (body.county) updates.county = String(body.county).slice(0, 200);
      if (body.charge) updates.charge = String(body.charge).slice(0, 300);
      if (body.court) updates.court = String(body.court).slice(0, 200);
      if (body.description !== undefined) updates.description = String(body.description).slice(0, 5000);
      if (body.next_hearing !== undefined) updates.next_hearing = body.next_hearing;
      if (body.tags) updates.tags = Array.isArray(body.tags) ? body.tags.slice(0, 10) : [];

      var { data, error } = await sb.from('cases')
        .update(updates)
        .eq('id', caseId)
        .eq('user_id', userId)
        .select()
        .single();
      if (error) throw error;

      return res.status(200).json({ case: data });
    }

    // DELETE /api/cases?id=xxx — archive (soft delete)
    if (req.method === 'DELETE') {
      var caseId = req.query.id;
      if (!caseId) return res.status(400).json({ error: 'Case ID required' });

      var { data, error } = await sb.from('cases')
        .update({ status: 'archived' })
        .eq('id', caseId)
        .eq('user_id', userId)
        .select()
        .single();
      if (error) throw error;

      return res.status(200).json({ case: data });
    }

    return res.status(405).json({ error: 'Method not allowed' });

  } catch (err) {
    console.error('Cases API error:', err);
    return res.status(500).json({ error: 'Server error: ' + err.message });
  }
};

async function logAdminAudit(sb, userId, action, entityType, entityId, details) {
  try {
    await sb.from('admin_audit_log').insert({
      admin_user_id: userId,
      action: action,
      entity_type: entityType,
      entity_id: entityId,
      details: details || {}
    });
  } catch (e) { /* non-critical */ }
}
