var { createClient } = require('@supabase/supabase-js');

// =====================================================================
// INVERITAS — UPL-SAFE DRAFT MOTION GENERATOR
// Implements Stanford CodeX Uncrossable Threshold (UT) framework
// Seven architectural principles enforced at the system level:
//   1. REFUSAL ARCHITECTURE — deterministic gates, no bypass
//   2. JURISDICTION SENSITIVITY — disclose what system doesn't know
//   3. NO TAILORED LEGAL CONCLUSIONS — information, not advice
//   4. COMPLETENESS GATING — refuse without sufficient evidence
//   5. STRUCTURAL HUMAN REVIEW CHECKPOINT — DRAFT formatting
//   6. CITATION INTEGRITY — verify flags on all citations
//   7. PRIVILEGE DISCLOSURE — not protected communication
// =====================================================================

// ===== PRINCIPLE 1: REFUSAL ARCHITECTURE =====
// Deterministic universal baseline gates — cannot be bypassed
var UNIVERSAL_REQUIRED_EVIDENCE = [
  {
    key: 'charging_document',
    label: 'Charging Document',
    description: 'Complaint, information, indictment, or citation',
    types: ['court_filing', 'document', 'other'],
    keywords: ['complaint', 'indictment', 'information', 'citation', 'charging', 'charge']
  },
  {
    key: 'pc_affidavit',
    label: 'Probable Cause Affidavit or Arrest Report',
    description: 'PC affidavit, arrest report, or officer narrative',
    types: ['police_report', 'court_filing', 'document'],
    keywords: ['probable cause', 'affidavit', 'arrest report', 'officer', 'narrative', 'pc affidavit', 'incident report']
  },
  {
    key: 'completed_analysis',
    label: 'Completed Inveritas Analysis',
    description: 'At least one statutory inversion analysis must be completed for this case',
    check: 'analysis_exists'
  }
];

// Motion-specific additional requirements
var MOTION_REQUIREMENTS = {
  motion_to_suppress: {
    label: 'Motion to Suppress Evidence',
    additional: [
      {
        key: 'encounter_narrative',
        label: 'Stop/Encounter Documentation',
        description: 'Dashcam, bodycam, officer report, or witness account of the initial encounter',
        types: ['video', 'police_report', 'witness_statement', 'photo'],
        keywords: ['dashcam', 'bodycam', 'body cam', 'dash cam', 'traffic stop', 'encounter', 'stop'],
        recommended: true
      }
    ]
  },
  motion_to_dismiss: {
    label: 'Motion to Dismiss',
    additional: []
  },
  motion_for_discovery: {
    label: 'Motion for Discovery',
    additional: []
  },
  motion_in_limine: {
    label: 'Motion in Limine',
    additional: [
      {
        key: 'evidence_at_issue',
        label: 'Evidence to Exclude/Include',
        description: 'The specific evidence item(s) this motion targets',
        types: ['document', 'photo', 'video', 'audio', 'medical_record', 'financial_record'],
        keywords: [],
        recommended: true
      }
    ]
  },
  motion_to_compel: {
    label: 'Motion to Compel',
    additional: []
  },
  motion_for_speedy_trial: {
    label: 'Motion for Speedy Trial',
    additional: []
  },
  motion_to_reduce_bond: {
    label: 'Motion to Reduce Bond',
    additional: []
  },
  motion_to_quash: {
    label: 'Motion to Quash',
    additional: []
  },
  motion_for_continuance: {
    label: 'Motion for Continuance',
    additional: []
  },
  general_motion: {
    label: 'General Motion',
    additional: []
  }
};

// ===== PRINCIPLE 3: NO TAILORED LEGAL CONCLUSIONS =====
// System prompt explicitly prohibits advice language
var GENERATION_SYSTEM_PROMPT = 'You are a legal document drafting assistant. You generate DRAFT legal documents based on case evidence and statutory analysis for informational purposes.\n\n' +
'CRITICAL UPL-SAFE ARCHITECTURE RULES — VIOLATION OF ANY RULE INVALIDATES THE OUTPUT:\n\n' +
'1. NEVER use advisory language. NEVER say "you should file this", "this motion will succeed", "the court will likely grant this", or any language suggesting a recommended course of action. Present arguments as "potential arguments available" not "your arguments."\n\n' +
'2. NEVER present yourself as an attorney, counselor, or legal advisor. You are a document formatting tool that structures legal research into standard motion format.\n\n' +
'3. EVERY case citation MUST include a verification status:\n' +
'   - If you are confident the citation is accurate: [VERIFIED — verify independently before filing]\n' +
'   - If you have any uncertainty: [UNVERIFIED — citation requires independent verification]\n' +
'   - NEVER present a citation without one of these tags\n\n' +
'4. The document MUST begin with this exact header (do not modify it):\n' +
'   ══════════════════════════════════════════════\n' +
'   DRAFT — FOR INFORMATIONAL PURPOSES ONLY\n' +
'   NOT LEGAL ADVICE — REQUIRES ATTORNEY REVIEW BEFORE FILING\n' +
'   Generated by Inveritas Legal Research Platform\n' +
'   This document does not create an attorney-client relationship\n' +
'   ══════════════════════════════════════════════\n\n' +
'5. The document MUST end with this exact footer (do not modify it):\n' +
'   ══════════════════════════════════════════════\n' +
'   DRAFT DOCUMENT — NOT FOR FILING WITHOUT ATTORNEY REVIEW\n' +
'   All citations marked [UNVERIFIED] require independent verification\n' +
'   This document was generated by artificial intelligence and may\n' +
'   contain inaccuracies, hallucinated citations, or errors of law.\n' +
'   Consult a licensed attorney before taking any legal action.\n' +
'   ══════════════════════════════════════════════\n\n' +
'6. DO NOT include a signature block. The user must add their own.\n\n' +
'7. Include a JURISDICTIONAL DISCLOSURE section after the header stating:\n' +
'   "This draft was generated for [State], [County/City]. Local court rules,\n' +
'   filing deadlines, formatting requirements, and procedural rules may differ\n' +
'   from the content of this draft. Verify all procedural requirements with\n' +
'   the clerk of court or a licensed attorney licensed in this jurisdiction."\n\n' +
'8. Format the motion in standard legal document format for the specified jurisdiction:\n' +
'   - Caption with court name, case style (use placeholder names: [DEFENDANT NAME] and [STATE/PLAINTIFF])\n' +
'   - Cause number placeholder: [CAUSE NO.]\n' +
'   - Standard sections: Introduction, Statement of Facts, Legal Authority, Argument, Prayer for Relief\n' +
'   - Prayer for Relief should be generic: "WHEREFORE, [DEFENDANT NAME] respectfully requests that this Court grant this motion."\n\n' +
'9. Base all arguments ONLY on the defense vectors, evidence, and analysis provided. Do not invent arguments beyond what the analysis supports.\n\n' +
'10. Return the document as clean text (not markdown, not JSON). Use standard legal formatting with numbered paragraphs.\n\n' +
'Generate the draft motion now based on the case data, evidence, and analysis provided.';


module.exports = async function handler(req, res) {
  // CORS
  var allowedOrigins = ['https://inveritaslaw.com', 'https://www.inveritaslaw.com'];
  var origin = req.headers.origin;
  if (allowedOrigins.indexOf(origin) >= 0) {
    res.setHeader('Access-Control-Allow-Origin', origin);
  } else if (process.env.VERCEL_ENV !== 'production') {
    res.setHeader('Access-Control-Allow-Origin', '*');
  }
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');

  if (req.method === 'OPTIONS') return res.status(200).end();

  var ANTHROPIC_KEY = process.env.ANTHROPIC_API_KEY;
  var SUPABASE_URL = process.env.SUPABASE_URL;
  var SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_KEY) {
    return res.status(500).json({ error: 'Server not configured' });
  }

  // ===== AUTH =====
  var authHeader = req.headers.authorization || '';
  var token = authHeader.replace('Bearer ', '');
  if (!token) return res.status(401).json({ error: 'Authentication required' });

  var sb = createClient(SUPABASE_URL, SUPABASE_KEY);
  var authResult = await sb.auth.getUser(token);
  if (authResult.error || !authResult.data.user) {
    return res.status(401).json({ error: 'Invalid session' });
  }
  var userId = authResult.data.user.id;

  // ===== GET: LIST / FETCH DOCUMENTS =====
  if (req.method === 'GET') {
    try {
      var caseId = req.query.case_id;
      if (!caseId) return res.status(400).json({ error: 'case_id required' });

      if (req.query.doc_id) {
        var docResult = await sb.from('generated_documents').select('*')
          .eq('id', req.query.doc_id).eq('user_id', userId).single();
        if (docResult.error || !docResult.data) return res.status(404).json({ error: 'Document not found' });
        return res.status(200).json({ document: docResult.data });
      }

      var listResult = await sb.from('generated_documents')
        .select('id, document_type, title, completeness_score, unverified_citation_count, verified_citation_count, jurisdiction_state, jurisdiction_county, created_at')
        .eq('case_id', caseId).eq('user_id', userId)
        .order('created_at', { ascending: false });
      if (listResult.error) throw listResult.error;
      return res.status(200).json({ documents: listResult.data || [] });
    } catch (err) {
      return res.status(500).json({ error: err.message });
    }
  }

  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  if (!ANTHROPIC_KEY) {
    return res.status(500).json({ error: 'API key not configured' });
  }

  // ===== SUBSCRIPTION CHECK =====
  var profileResult = await sb.from('user_profiles')
    .select('subscription_tier, analyses_this_month')
    .eq('user_id', userId).single();

  if (!profileResult.data) {
    return res.status(403).json({ error: 'No subscription found' });
  }

  var tier = profileResult.data.subscription_tier || 'none';
  // Document generation requires practitioner or higher
  if (tier === 'none' || tier === 'single') {
    return res.status(403).json({
      error: 'Draft motion generation requires a Practitioner ($297/mo) or higher subscription.',
      upgrade_required: true
    });
  }

  try {
    var body = req.body || {};
    var caseId = body.case_id;
    var motionType = body.motion_type;
    var additionalContext = body.additional_context || '';

    if (!caseId) return res.status(400).json({ error: 'case_id required' });
    if (!motionType) return res.status(400).json({ error: 'motion_type required' });
    if (!MOTION_REQUIREMENTS[motionType]) {
      return res.status(400).json({ error: 'Invalid motion type: ' + motionType });
    }

    // ===== CHECK MODE — return completeness without generating =====
    if (body.action === 'check') {
      var checkCaseResult = await sb.from('cases')
        .select('*').eq('id', caseId).eq('user_id', userId).single();
      if (checkCaseResult.error || !checkCaseResult.data) {
        return res.status(404).json({ error: 'Case not found' });
      }
      var checkEvResult = await sb.from('evidence')
        .select('id, title, description, evidence_type, file_name, source, collected_by, collected_at, sha256_hash')
        .eq('case_id', caseId).order('created_at', { ascending: true });
      var checkAnalysisResult = await sb.from('case_analyses')
        .select('id, version, result, created_at')
        .eq('case_id', caseId).eq('user_id', userId)
        .order('version', { ascending: false }).limit(1);
      var checkAnalysis = (checkAnalysisResult.data && checkAnalysisResult.data.length > 0) ? checkAnalysisResult.data[0] : null;
      var checkCompleteness = assessCompleteness(checkEvResult.data || [], checkAnalysis, motionType);

      // Also return available motion types from latest analysis
      var availableMotions = [];
      if (checkAnalysis && checkAnalysis.result && checkAnalysis.result.recommended_motions) {
        availableMotions = checkAnalysis.result.recommended_motions;
      }

      return res.status(200).json({
        completeness: checkCompleteness,
        motion_type: motionType,
        motion_label: MOTION_REQUIREMENTS[motionType].label,
        available_motions: availableMotions,
        evidence_count: (checkEvResult.data || []).length,
        has_analysis: !!checkAnalysis
      });
    }

    // ===== PRINCIPLE 7: PRIVILEGE DISCLOSURE =====
    // Verify user acknowledged privilege warning
    if (!body.privilege_acknowledged) {
      return res.status(400).json({
        error: 'privilege_required',
        message: 'You must acknowledge that documents generated through Inveritas are NOT protected by attorney-client privilege before proceeding. Content submitted to and generated by this platform may be discoverable.'
      });
    }

    // Verify user acknowledged UPL disclaimer
    if (!body.upl_acknowledged) {
      return res.status(400).json({
        error: 'upl_required',
        message: 'You must acknowledge that generated documents are drafts for informational purposes only, not legal advice, and require review by a licensed attorney before filing.'
      });
    }

    // ===== LOAD CASE DATA =====
    var caseResult = await sb.from('cases')
      .select('*').eq('id', caseId).eq('user_id', userId).single();

    if (caseResult.error || !caseResult.data) {
      return res.status(404).json({ error: 'Case not found' });
    }
    var caseData = caseResult.data;

    // Load evidence
    var evResult = await sb.from('evidence')
      .select('id, title, description, evidence_type, file_name, source, collected_by, collected_at, sha256_hash')
      .eq('case_id', caseId).order('created_at', { ascending: true });
    var evidence = evResult.data || [];

    // Load latest analysis
    var analysisResult = await sb.from('case_analyses')
      .select('*')
      .eq('case_id', caseId).eq('user_id', userId)
      .order('version', { ascending: false }).limit(1);
    var latestAnalysis = (analysisResult.data && analysisResult.data.length > 0) ? analysisResult.data[0] : null;

    // ===== PRINCIPLE 1 + 4: COMPLETENESS GATING =====
    var completeness = assessCompleteness(evidence, latestAnalysis, motionType);

    if (!completeness.pass) {
      return res.status(400).json({
        error: 'completeness_failed',
        message: 'Case file does not meet minimum requirements for draft generation.',
        completeness: completeness
      });
    }

    // ===== PRINCIPLE 2: JURISDICTION SENSITIVITY =====
    var jurisdictionDisclosure = 'This draft was generated for ' +
      (caseData.state || '[STATE NOT SPECIFIED]') + ', ' +
      (caseData.county || '[COUNTY/CITY NOT SPECIFIED]') + '. ' +
      'Local court rules, filing deadlines, formatting requirements, and procedural rules may differ from the content of this draft. ' +
      'Verify all procedural requirements with the clerk of court or a licensed attorney licensed in this jurisdiction. ' +
      'This system does not have access to local court rules, standing orders, or judge-specific preferences for ' +
      (caseData.county || 'this jurisdiction') + '.';

    // ===== BUILD GENERATION PROMPT =====
    var motionLabel = MOTION_REQUIREMENTS[motionType].label;

    var prompt = 'CASE INFORMATION:\n';
    prompt += 'State: ' + (caseData.state || 'Not specified') + '\n';
    prompt += 'County/City: ' + (caseData.county || 'Not specified') + '\n';
    prompt += 'Charge: ' + (caseData.charge || 'Not specified') + '\n';
    prompt += 'Court: ' + (caseData.court || 'Not specified') + '\n';
    prompt += 'Case Type: ' + (caseData.case_type || 'criminal') + '\n';
    prompt += '\nCASE DESCRIPTION:\n' + (caseData.description || 'No description provided.') + '\n';

    if (additionalContext) {
      prompt += '\nADDITIONAL CONTEXT FOR THIS MOTION:\n' + String(additionalContext).slice(0, 3000) + '\n';
    }

    // Evidence summary
    prompt += '\nEVIDENCE ON FILE (' + evidence.length + ' items):\n';
    evidence.forEach(function(ev, i) {
      prompt += '  ' + (i + 1) + '. [' + (ev.evidence_type || 'document').toUpperCase() + '] ' + ev.title;
      if (ev.description) prompt += ' — ' + ev.description;
      if (ev.source) prompt += ' (Source: ' + ev.source + ')';
      prompt += '\n';
    });

    // Analysis results
    if (latestAnalysis && latestAnalysis.result) {
      var r = latestAnalysis.result;
      prompt += '\nSTATUTORY INVERSION ANALYSIS (Version ' + latestAnalysis.version + '):\n';

      if (r.charge_analysis) {
        prompt += '\nCharge: ' + (r.charge_analysis.offense || '') + '\n';
        prompt += 'Governing Statute: ' + (r.charge_analysis.governing_statute || '') + '\n';
        prompt += 'Severity: ' + (r.charge_analysis.severity_class || '') + '\n';
        if (r.charge_analysis.elements_required) {
          prompt += '\nElements Prosecution Must Prove:\n';
          r.charge_analysis.elements_required.forEach(function(el, i) {
            prompt += '  ' + (i + 1) + '. ' + el + '\n';
          });
        }
      }

      if (r.tier_conflict_opportunities && r.tier_conflict_opportunities.length > 0) {
        prompt += '\nTier Conflict Opportunities:\n';
        r.tier_conflict_opportunities.forEach(function(tc, i) {
          prompt += '  ' + (i + 1) + '. ' + tc + '\n';
        });
      }

      if (r.inversion_vectors && r.inversion_vectors.length > 0) {
        prompt += '\nDefense Inversion Vectors:\n';
        r.inversion_vectors.forEach(function(v, i) {
          prompt += '  ' + (i + 1) + '. [' + (v.category || '') + '] [' + (v.legal_tier || '') + '] ' + v.title + ' (Confidence: ' + v.confidence + '%)\n';
          if (v.applicable_law) prompt += '     Law: ' + v.applicable_law + '\n';
          prompt += '     ' + v.argument + '\n';
        });
      }

      if (r.statutory_escape_hatches && r.statutory_escape_hatches.length > 0) {
        prompt += '\nStatutory Escape Hatches:\n';
        r.statutory_escape_hatches.forEach(function(h, i) { prompt += '  ' + (i + 1) + '. ' + h + '\n'; });
      }

      if (r.prosecution_weaknesses && r.prosecution_weaknesses.length > 0) {
        prompt += '\nProsecution Weaknesses:\n';
        r.prosecution_weaknesses.forEach(function(w, i) { prompt += '  ' + (i + 1) + '. ' + w + '\n'; });
      }
    }

    prompt += '\nDOCUMENT TO GENERATE: ' + motionLabel + '\n';
    prompt += 'JURISDICTION: ' + (caseData.state || '') + ', ' + (caseData.county || '') + '\n';
    prompt += '\nGenerate a properly formatted ' + motionLabel + ' incorporating the relevant defense vectors and evidence listed above. Follow all UPL-safe formatting rules from your instructions.';

    // ===== CALL ANTHROPIC =====
    // Keepalive for Vercel timeout
    res.setHeader('Content-Type', 'application/json');
    res.setHeader('Cache-Control', 'no-store');

    var keepaliveTimer = setInterval(function() { res.write(' '); }, 3000);

    var apiResponse = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': ANTHROPIC_KEY,
        'anthropic-version': '2023-06-01'
      },
      body: JSON.stringify({
        model: 'claude-sonnet-4-20250514',
        max_tokens: 8192,
        system: GENERATION_SYSTEM_PROMPT,
        messages: [{ role: 'user', content: prompt }]
      })
    });

    clearInterval(keepaliveTimer);

    var apiData = await apiResponse.json();

    if (apiData.error) {
      return res.end(JSON.stringify({ error: 'Generation service error: ' + (apiData.error.message || 'Unknown') }));
    }

    // Extract text
    var generatedText = '';
    if (apiData.content && Array.isArray(apiData.content)) {
      for (var i = 0; i < apiData.content.length; i++) {
        if (apiData.content[i].type === 'text') generatedText += apiData.content[i].text;
      }
    }

    if (!generatedText || generatedText.length < 100) {
      return res.end(JSON.stringify({ error: 'Generation produced insufficient output. Please try again.' }));
    }

    // ===== PRINCIPLE 6: CITATION INTEGRITY AUDIT =====
    var verifiedCount = (generatedText.match(/\[VERIFIED/g) || []).length;
    var unverifiedCount = (generatedText.match(/\[UNVERIFIED/g) || []).length;

    // ===== SAVE TO DATABASE =====
    var evidenceSnapshot = evidence.map(function(ev) {
      return { id: ev.id, title: ev.title, type: ev.evidence_type, hash: ev.sha256_hash };
    });

    var uplCompliance = {
      refusal_gate_passed: true,
      completeness_score: completeness.score,
      completeness_details: completeness,
      jurisdiction_disclosure_included: true,
      privilege_acknowledged: true,
      privilege_acknowledged_at: new Date().toISOString(),
      upl_acknowledged: true,
      upl_acknowledged_at: new Date().toISOString(),
      draft_header_required: true,
      draft_footer_required: true,
      no_signature_block: true,
      citation_flags_required: true,
      verified_citations: verifiedCount,
      unverified_citations: unverifiedCount,
      model_version: 'claude-sonnet-4-20250514',
      generated_at: new Date().toISOString(),
      architectural_principles: [
        'refusal_architecture',
        'jurisdiction_sensitivity',
        'no_tailored_conclusions',
        'completeness_gating',
        'structural_human_review',
        'citation_integrity',
        'privilege_disclosure'
      ]
    };

    var saveResult = await sb.from('generated_documents').insert({
      case_id: caseId,
      user_id: userId,
      document_type: motionType,
      title: motionLabel + ' — ' + (caseData.title || 'Case'),
      completeness_score: completeness.score,
      completeness_details: completeness,
      evidence_snapshot: evidenceSnapshot,
      source_analysis_id: latestAnalysis ? latestAnalysis.id : null,
      source_analysis_version: latestAnalysis ? latestAnalysis.version : null,
      content: generatedText,
      content_format: 'text',
      upl_compliance: uplCompliance,
      jurisdiction_state: caseData.state,
      jurisdiction_county: caseData.county,
      jurisdiction_disclosure: jurisdictionDisclosure,
      citations: { verified: verifiedCount, unverified: unverifiedCount },
      unverified_citation_count: unverifiedCount,
      verified_citation_count: verifiedCount
    }).select().single();

    // Increment usage
    await sb.rpc('increment_analysis_count', { p_user_id: userId });

    // Audit log
    await sb.from('admin_audit_log').insert({
      admin_user_id: userId,
      action: 'document_generated',
      entity_type: 'generated_document',
      entity_id: saveResult.data ? saveResult.data.id : 'unknown',
      details: {
        motion_type: motionType,
        case_id: caseId,
        completeness_score: completeness.score,
        verified_citations: verifiedCount,
        unverified_citations: unverifiedCount
      }
    });

    return res.end(JSON.stringify({
      document: {
        id: saveResult.data ? saveResult.data.id : null,
        title: motionLabel,
        content: generatedText,
        completeness_score: completeness.score,
        jurisdiction_disclosure: jurisdictionDisclosure,
        citations: { verified: verifiedCount, unverified: unverifiedCount },
        upl_compliance: uplCompliance,
        created_at: new Date().toISOString()
      }
    }));

  } catch (err) {
    console.error('Generate motion error:', err);
    return res.status(500).json({ error: 'Server error: ' + err.message });
  }
};

// ===== COMPLETENESS ASSESSMENT ENGINE =====
function assessCompleteness(evidence, latestAnalysis, motionType) {
  var result = {
    score: 0,
    pass: false,
    threshold: 70,
    universal_gates: [],
    motion_specific: [],
    missing: [],
    recommendations: []
  };

  var totalPoints = 0;
  var earnedPoints = 0;

  // ===== UNIVERSAL GATES (must all pass) =====
  var universalPass = true;

  // Gate 1: Charging document
  var hasCharging = false;
  for (var i = 0; i < evidence.length; i++) {
    var ev = evidence[i];
    var titleLower = (ev.title || '').toLowerCase();
    var descLower = (ev.description || '').toLowerCase();
    var typeLower = (ev.evidence_type || '').toLowerCase();
    var combined = titleLower + ' ' + descLower;

    if (typeLower === 'court_filing' ||
        combined.indexOf('complaint') >= 0 ||
        combined.indexOf('indictment') >= 0 ||
        combined.indexOf('information') >= 0 ||
        combined.indexOf('citation') >= 0 ||
        combined.indexOf('charging') >= 0) {
      hasCharging = true;
      break;
    }
  }
  totalPoints += 30;
  if (hasCharging) {
    earnedPoints += 30;
    result.universal_gates.push({ key: 'charging_document', label: 'Charging Document', status: 'met' });
  } else {
    universalPass = false;
    result.universal_gates.push({ key: 'charging_document', label: 'Charging Document', status: 'missing' });
    result.missing.push('Upload the charging document (complaint, citation, indictment, or information)');
  }

  // Gate 2: PC affidavit / arrest report
  var hasPC = false;
  for (var i = 0; i < evidence.length; i++) {
    var ev = evidence[i];
    var titleLower = (ev.title || '').toLowerCase();
    var descLower = (ev.description || '').toLowerCase();
    var typeLower = (ev.evidence_type || '').toLowerCase();
    var combined = titleLower + ' ' + descLower;

    if (typeLower === 'police_report' ||
        combined.indexOf('probable cause') >= 0 ||
        combined.indexOf('pc affidavit') >= 0 ||
        combined.indexOf('arrest report') >= 0 ||
        combined.indexOf('officer report') >= 0 ||
        combined.indexOf('officer narrative') >= 0 ||
        combined.indexOf('incident report') >= 0 ||
        combined.indexOf('offense report') >= 0) {
      hasPC = true;
      break;
    }
  }
  totalPoints += 30;
  if (hasPC) {
    earnedPoints += 30;
    result.universal_gates.push({ key: 'pc_affidavit', label: 'Probable Cause Affidavit / Arrest Report', status: 'met' });
  } else {
    universalPass = false;
    result.universal_gates.push({ key: 'pc_affidavit', label: 'Probable Cause Affidavit / Arrest Report', status: 'missing' });
    result.missing.push('Upload the probable cause affidavit, arrest report, or officer narrative');
  }

  // Gate 3: Completed analysis
  totalPoints += 20;
  if (latestAnalysis && latestAnalysis.result) {
    earnedPoints += 20;
    result.universal_gates.push({ key: 'completed_analysis', label: 'Completed Inveritas Analysis', status: 'met' });
  } else {
    universalPass = false;
    result.universal_gates.push({ key: 'completed_analysis', label: 'Completed Inveritas Analysis', status: 'missing' });
    result.missing.push('Run a statutory inversion analysis on this case before generating documents');
  }

  // ===== MOTION-SPECIFIC REQUIREMENTS =====
  var motionReqs = MOTION_REQUIREMENTS[motionType];
  if (motionReqs && motionReqs.additional) {
    motionReqs.additional.forEach(function(req) {
      var found = false;
      for (var i = 0; i < evidence.length; i++) {
        var ev = evidence[i];
        var titleLower = (ev.title || '').toLowerCase();
        var descLower = (ev.description || '').toLowerCase();
        var typeLower = (ev.evidence_type || '').toLowerCase();
        var combined = titleLower + ' ' + descLower;

        // Check type match
        if (req.types && req.types.indexOf(typeLower) >= 0) { found = true; break; }
        // Check keyword match
        if (req.keywords) {
          for (var k = 0; k < req.keywords.length; k++) {
            if (combined.indexOf(req.keywords[k]) >= 0) { found = true; break; }
          }
          if (found) break;
        }
      }

      totalPoints += 20;
      if (found) {
        earnedPoints += 20;
        result.motion_specific.push({ key: req.key, label: req.label, status: 'met' });
      } else if (req.recommended) {
        // Recommended but not blocking — partial credit
        earnedPoints += 5;
        result.motion_specific.push({ key: req.key, label: req.label, status: 'recommended' });
        result.recommendations.push('Recommended: Upload ' + req.label.toLowerCase() + ' — ' + req.description);
      } else {
        result.motion_specific.push({ key: req.key, label: req.label, status: 'missing' });
        result.missing.push('Upload ' + req.label.toLowerCase() + ': ' + req.description);
      }
    });
  }

  // Additional evidence bonus
  var extraEvidence = evidence.length - (hasCharging ? 1 : 0) - (hasPC ? 1 : 0);
  if (extraEvidence > 0) {
    var bonus = Math.min(extraEvidence * 5, 20);
    totalPoints += 20;
    earnedPoints += bonus;
  }

  // Calculate score
  result.score = totalPoints > 0 ? Math.round((earnedPoints / totalPoints) * 100) : 0;

  // ===== PRINCIPLE 1: DETERMINISTIC GATE — universal gates must ALL pass =====
  // Score must also meet threshold
  result.pass = universalPass && result.score >= result.threshold;

  return result;
}

module.exports.config = {
  api: { bodyParser: { sizeLimit: '5mb' } },
  maxDuration: 60
};
